### ISSUE TITLE
Apparently, Burning Oil Mana Cost is 1

### ISSUE THREAD

**Issue by g3neralz** [ottah/ArtifactDB#18]
https://github.com/ottah/ArtifactDB/blob/04d8ed483b3d683e3bde3cb437f515839a749550/cards-manifest.json#L661

Hi @ottah !

I've been told recently that Burning Oil (Red Improvement) Mana Cost is 1. It's quite confusing as different websites are showing different values (1 and 3). However, someone from the Beta confirmed on Discord that its 1

Thx for this DB btw, I built http://artifactgames.guru/mana.html based on this json manifest.

**Comment by 0ttah** [comment]
Thanks for letting me know, I just happened to be in your thread as you posted this. I've updated the mana https://github.com/ottah/ArtifactDB/commit/a89955f75a0249b7190fdd4ec341c53b1d5013fd. 
 Going to push to npm soon.

The site looks good keep up the good work.
