### ISSUE TITLE
Missing art for all the cards added in commit ea3edf1

### ISSUE THREAD

**Issue by bubblebooy** [ottah/ArtifactDB#29]
#26 
Cards need Large artwork , Small artwork, and associated hero abilities need artwork
- [x] Assassin's Veil
- [x] Assassinate
- [x] Astral Imprisionment
- [x] Ball Lightning
- [x] Bracers of Sacrifice
- [x] Broadsword
- [x] Buying Time
- [x] Claymore
- [x] Cloak of Endless Carnage
- [x] Collateral Damage
- [x] Combat Training
- [x] Dirty Deeds
- [x] Empower
- [x] Fight Through the Pain
- [x] Fountain Flas
- [x] Friendly Fire
- [x] Healing Salve
- [x] Hero's Cape
- [x] Heroic Resolve
- [x] Incarnation of Selemene
- [x] Keenfolk Golem
- [x] Keenfolk Plate
- [x] Magnus
- [x] Mazzie
- [ ] Melee Creep Dire
- [x] Messenger Rookery
- [x] Murder Plot
- [x] Nyctasha's Guard
- [x] Oglodi Catapult
- [x] Outworld Devourer
- [x] Pick a Fight
- [x] Platemail
- [x] Potion of Knowledge
- [x] Relentless Pursuit
- [x] Rising Anger
- [x] Rumusque Vestments
- [x] Shiva's Guard
- [x] Smeevil Armsmaster
- [x] Sniper
- [x] Steel Reinforcement
- [x] Stonehall Pike
- [x] Storm Spirit
- [x] Town Portal Scroll
- [x] Trebuchets
- [x] Tyler Estate Censor
- [x] Unsupervised Artillery
- [x] Vesture of the Tyrant
- [x] Wingfall Hammer

**Comment by 0ttah** [comment]
Added for all these cards except:
- Melee Creep Dire
- Oglodi Catapult

As they seem to not be available on any sites yet.

**Comment by bubblebooy** [comment]
Oglodi Catapult used to be called Horde Catapult. The art could probably be found under that name, unless they also changed the art when they changed the name.

**Comment by 0ttah** [comment]
Ah yeah the art is in the assets folder under the old name. I'll rename it now.
https://github.com/ottah/ArtifactDB/blob/master/assets/artwork/large/horde_catapult.jpg

**Comment by bubblebooy** [comment]
Ahh, they are both in the card-manifest too.

**Comment by 0ttah** [comment]
Yep removed them and renamed the files. Pushing to npm now.
