### ISSUE TITLE
card rankings

### ISSUE THREAD

**Issue by wakamex** [ottah/ArtifactDB#6]
would you be interested in maintaining tier lists published by third parties in this DB's schema? would have to add a field for each rater. we have a few already we could start populating, i.e. crokey, stancifka

**Comment by 0ttah** [comment]
Hi,
That is something that's out of scope of this project. I want to try an keep the repository focused on in game assets and values. Would be cool if you set one up though? I'm sure card rating sites are going to be popular when the game releases just like with MTG/HS.
